apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
#  type: NodePort
#  ports:
#  - port: 80
#    targetPort: 80
#    nodePort: 30007
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: netflix-app
